apiVersion: v1
kind: ConfigMap
metadata:
  name: filebeat-config
data:
  filebeat.yml: |
    filebeat.inputs:
    - type: log
      paths:
        - /app/logs/record.log
      fields:
        app: pythonapp

    output.elasticsearch:
      hosts: ["54.87.129.110:9200"]
---
apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app: mongo-app
  name: mongo-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mongo-app
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: mongo-app
    spec:
      containers:
      - image: daniellosev/weather:mongoapp
        name: weather
        volumeMounts:
        - name: mongo-data
          mountPath: /app/logs
        resources: {}
        - name: filebeat
          image: docker.elastic.co/beats/filebeat:7.12.1
          volumeMounts:
            - name: pythonapp-volume
              mountPath: /logs
              readOnly: true
            - name: filebeat-config
              mountPath: /usr/share/filebeat/filebeat.yml
              subPath: filebeat.yml
          env:
            - name: ELASTICSEARCH_HOST
              value: elasticsearch-cluster
            - name: ELASTICSEARCH_PORT
              value: "9200"
            - name: ELASTICSEARCH_USERNAME
              value: elastic
            - name: ELASTICSEARCH_PASSWORD
              value: changeme
            - name: ELASTICSEARCH_INDEX
              value: pythonapp
          args: [
            "-e", 
            "-c", "/usr/share/filebeat/filebeat.yml"
          ]
      volumes: 
        - name: filebeat-config
          configMap:
            name: filebeat-config
---
apiVersion: v1
kind: Service
metadata:
  name: mongo-service
spec:
  selector:
    app: mongo-app
  ports:
  - name: app-port
    port: 5000
    targetPort: 5000
  type: LoadBalancer








