apiVersion: v1
kind: ConfigMap
metadata:
  name: filebeat-config
data:
  filebeat.yml: |
    filebeat.inputs:
    - type: log
      paths:
        - /usr/share/filebeat/app/logs/record.log
      fields:
        app: pythonapp

    output.elasticsearch:
      hosts: ["18.212.48.240:9200"]
      username: "elastic"
      password: "changeme"

---
apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app: mongo-app
  name: mongo-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mongo-app
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: mongo-app
    spec:
      containers:
      - image: daniellosev/weather:mongoapp
        name: weather
        ports:
        - containerPort: 5000
        volumeMounts:
        - name: logs-volume
          mountPath: /app/logs
      - name: filebeat
        image: docker.elastic.co/beats/filebeat:7.12.1
        volumeMounts:
        - name: filebeat-config
          mountPath: /usr/share/filebeat/filebeat.yml
          subPath: filebeat.yml
        - name: logs-volume
          mountPath: /usr/share/filebeat/app/logs
        env:
        - name: ELASTICSEARCH_HOST
          value: elasticsearch-cluster
        - name: ELASTICSEARCH_PORT
          value: "9200"
        - name: ELASTICSEARCH_USERNAME
          value: elastic
        - name: ELASTICSEARCH_PASSWORD
          value: changeme
        - name: ELASTICSEARCH_INDEX
          value: pythonapp
        args: [
          "-e", 
          "-c", "/usr/share/filebeat/filebeat.yml"
        ]
      volumes: 
      - name: mongo-data
        emptyDir: {}
      - name: pythonapp-volume
        configMap:
          name: pythonapp-config
      - name: filebeat-config
        configMap:
          name: filebeat-config
      - name: logs-volume
        emptyDir: {}
      
---
apiVersion: v1
kind: Service
metadata:
  name: mongo-service
spec:
  selector:
    app: mongo-app
  ports:
  - name: app-port
    port: 5000
    targetPort: 5000
  type: LoadBalancer











