apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app: mongo-app
  name: mongo-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mongo-app
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: mongo-app
    spec:
      containers:
      - image: daniellosev/weather:mongoapp
        name: weather
        volumeMounts:
        - name: mongo-data
          mountPath: /app/logs
        resources: {}
      volumes:
      - name: mongo-data
        persistentVolumeClaim:
          claimName: pythonapp-pvc
      restartPolicy: Always





---

apiVersion: v1
kind: Service
metadata:
  name: mongo-service
spec:
  selector:
    app: mongo-app
  ports:
  - name: app-port
    port: 5000
    targetPort: 5000
  type: LoadBalancer
  
---  
  
apiVersion: v1
kind: PersistentVolume
metadata:
  name: pythonapp-p
spec:
  capacity:
    storage: 10Gi
  accessModes:
    - ReadWriteOnce
  awsElasticBlockStore:
    volumeID: vol-0d059b7b12ec4cade
    fsType: ext4
  storageClassName: pythonapp-storageclass

    
---  
  
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: pythonapp-pvc
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 2Gi
  storageClassName: pythonapp-storageclass
  
  
---

apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: pythonapp-storageclass
provisioner: kubernetes.io/aws-ebs
parameters:
  type: gp2
reclaimPolicy: Retain
mountOptions:
  - debug
volumeBindingMode: Immediate






