apiVersion: v1
kind: PersistentVolume
metadata:
  name: pythonapp-p
spec:
  capacity:
    storage: 10Gi
  accessModes:
    - ReadWriteOnce
  awsElasticBlockStore:
    volumeID: vol-0d059b7b12ec4cade
    fsType: ext4
  storageClassName: pythonapp-storageclass

    
---  
  
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: pythonapp-pvc
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 2Gi
  storageClassName: pythonapp-storageclass
  
  
---

apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: pythonapp-storageclass
provisioner: kubernetes.io/aws-ebs
parameters:
  type: gp2
reclaimPolicy: Retain
mountOptions:
  - debug
volumeBindingMode: Immediate

